name: GitHub Metrics

on:
  # Runs every night at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # This connects to the secret we just made!
          token: ${{ secrets.METRICS_TOKEN }}
          
          # General configuration
          user: patel-mark
          template: classic
          base: header, activity, community, repositories
          config_timezone: Africa/Nairobi
          
          # Replaces Top Languages card
          plugin_languages: yes
          plugin_languages_colors: github
          
          # Replaces Trophies card
          plugin_achievements: yes
          plugin_achievements_display: detailed
          
          # Replaces Streak card (Shows a 3D isometric calendar of your commits)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
